# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outras_entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outraentrada',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Received'), ('PENDENTE', 'Pending')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='outraentradainstallment',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Received'), ('PENDENTE', 'Pending')], default='PENDENTE', max_length=20),
        ),
    ]
