# Generated by Django 6.0.6 on 2026-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outras_entradas', '0002_alter_outraentrada_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outraentradainstallment',
            index=models.Index(fields=['due_date', 'status'], name='outra_ent_due_status_idx'),
        ),
    ]
