# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreportsummary',
            name='expenses_late_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Late Interest'),
        ),
        migrations.AlterField(
            model_name='financialreportsummary',
            name='expenses_payroll',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='People/Payroll'),
        ),
        migrations.AlterField(
            model_name='financialreportsummary',
            name='expenses_structure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Structure/Office'),
        ),
        migrations.AlterField(
            model_name='financialreportsummary',
            name='expenses_taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Taxes'),
        ),
    ]
