# Generated by Django 6.0.4 on 2026-06-05 19:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios', '0002_honorario_interest_rate_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total contract/fee amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='date',
            field=models.DateField(help_text='Contract base date or first due date'),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='interest_rate_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly late interest/penalty percentage (example: 2.00 for 2%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='is_installment',
            field=models.BooleanField(default=False, help_text='Indicates whether this fee is paid in installments'),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pending'), ('RECEBIDO', 'Received')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='total_installments',
            field=models.PositiveIntegerField(default=1, help_text='Total number of installments'),
        ),
        migrations.AlterField(
            model_name='parcelahonorario',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Specific amount for this installment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='parcelahonorario',
            name='due_date',
            field=models.DateField(help_text='Installment due date'),
        ),
        migrations.AlterField(
            model_name='parcelahonorario',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pending'), ('RECEBIDO', 'Received')], default='PENDENTE', max_length=20),
        ),
    ]
