# Generated by Django 6.0.6 on 2026-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios', '0003_alter_honorario_amount_alter_honorario_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcelahonorario',
            index=models.Index(fields=['due_date', 'status'], name='parc_hon_due_status_idx'),
        ),
    ]
