# Generated by Django 6.0.4 on 2026-05-26 22:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0005_remove_expensedeferral_expense_and_more'),
        ('firms', '0002_alter_firm_type_alter_firmmember_role'),
        ('honorarios', '0002_honorario_interest_rate_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Itaú Escritório, Caixinha Coletiva', max_length=100)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('INVESTMENT', 'Investimentos'), ('CASH', 'Dinheiro em Espécie')], default='CHECKING', max_length=20)),
                ('provider_name', models.CharField(blank=True, help_text='Nome do banco no Open Finance (Ex: Bradesco)', max_length=100)),
                ('external_account_id', models.CharField(blank=True, help_text='ID da conta na API do Open Finance', max_length=255, null=True, unique=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='firms.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('INFLOW', 'Receita (Entrada)'), ('OUTFLOW', 'Despesa (Saída)')], max_length=10)),
                ('date', models.DateField(help_text='Data da efetivação financeira')),
                ('external_transaction_id', models.CharField(blank=True, help_text='ID da transação no extrato do Open Finance', max_length=255, null=True, unique=True)),
                ('is_reconciled', models.BooleanField(default=False, help_text='Define se a transação bancária real foi batida com o sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dinheiro.bankaccount')),
                ('expense_installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.parceladespesa')),
                ('fee_installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='honorarios.parcelahonorario')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
