# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolabore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prolaboresimulation',
            name='perfil_estagio',
            field=models.CharField(choices=[('INICIANTE', 'Beginner'), ('INTERMEDIARIO', 'Intermediate'), ('AVANCADO', 'Advanced')], default='INTERMEDIARIO', max_length=20),
        ),
    ]
