# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinheiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings'), ('INVESTMENT', 'Investments'), ('CASH', 'Cash')], default='CHECKING', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='external_account_id',
            field=models.CharField(blank=True, help_text='Account ID in the Open Finance API', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(help_text='Example: Office Bank, Shared Cash Box', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='provider_name',
            field=models.CharField(blank=True, help_text='Bank name in Open Finance (example: Bradesco)', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(help_text='Financial settlement date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID in the Open Finance statement', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text='Indicates whether the bank transaction has been reconciled with the system'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INFLOW', 'Income (Inflow)'), ('OUTFLOW', 'Expense (Outflow)')], max_length=10),
        ),
    ]
