# Generated by Django 6.0.6 on 2026-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinheiro', '0002_alter_bankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name']},
        ),
    ]
