# Generated by Django 6.0.4 on 2026-05-23 15:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='interest_rate_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de juros/multa por mês de atraso (Ex: 2.00 para 2%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='honorario',
            name='is_installment',
            field=models.BooleanField(default=False, help_text='Flag indicando se é parcelado'),
        ),
        migrations.AddField(
            model_name='honorario',
            name='total_installments',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade total de parcelas'),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do contrato/honorário', max_digits=12),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='date',
            field=models.DateField(help_text='Data base do contrato ou primeiro vencimento'),
        ),
        migrations.CreateModel(
            name='ParcelaHonorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor específico desta parcela', max_digits=12)),
                ('due_date', models.DateField(help_text='Data de vencimento da parcela')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido')], default='PENDENTE', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('honorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='honorarios.honorario')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
    ]
