# Generated by Django 6.0.4 on 2026-05-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyerprofile',
            old_name='bank_name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='office_address',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='complement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='tax_regime',
            field=models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real'), ('AUTONOMO_PF', 'Autônomo (Pessoa Física)')], default='AUTONOMO_PF', max_length=30),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='average_monthly_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Despesa Média'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='average_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Receita Média'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='financial_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Meta Financeira Mensal (Opcional)'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='goal_type',
            field=models.CharField(choices=[('SURVIVAL', 'Sobrevivência - Quitar dívidas e manter o escritório operando'), ('STABILITY', 'Estabilidade - Construir uma prática financeira sólida e previsível'), ('GROWTH', 'Crescimento - Escalar o escritório e aumentar a receita')], default='STABILITY', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='income_variability',
            field=models.CharField(choices=[('LOW', 'Baixa - Previsível'), ('MEDIUM', 'Média - Alguma variação'), ('HIGH', 'Alta - Muito variável')], default='HIGH', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='office_type',
            field=models.CharField(choices=[('HOME', 'Home Office'), ('PHYSICAL', 'Escritório Físico')], default='HOME', max_length=20),
        ),
    ]
