# Generated by Django 6.0.4 on 2026-05-24 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_plan_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_due_alerts', models.BooleanField(default=True)),
                ('days_advance_taxes', models.PositiveIntegerField(default=5, help_text='Antecedência para Impostos (dias)')),
                ('days_advance_rent', models.PositiveIntegerField(default=3, help_text='Antecedência para Aluguel (dias)')),
                ('days_advance_others', models.PositiveIntegerField(default=1, help_text='Antecedência para Outros (dias)')),
                ('enable_approval_requests', models.BooleanField(default=True)),
                ('enable_weekly_summary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
