# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_lawyerprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='goal_type',
            field=models.CharField(choices=[('SURVIVAL', 'Survival - Pay off debts and keep the office operating'), ('STABILITY', 'Stability - Build a solid and predictable financial practice'), ('GROWTH', 'Growth - Scale the office and increase revenue')], default='STABILITY', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='income_variability',
            field=models.CharField(choices=[('LOW', 'Low - Predictable'), ('MEDIUM', 'Medium - Some variation'), ('HIGH', 'High - Very variable')], default='HIGH', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='office_type',
            field=models.CharField(choices=[('HOME', 'Home Office'), ('PHYSICAL', 'Physical Office')], default='HOME', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='tax_regime',
            field=models.CharField(choices=[('SIMPLES', 'Simplified National Regime'), ('LUCRO_PRESUMIDO', 'Presumed Profit'), ('LUCRO_REAL', 'Actual Profit'), ('AUTONOMO_PF', 'Self-employed (Individual)')], default='AUTONOMO_PF', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='days_advance_others',
            field=models.PositiveIntegerField(default=1, help_text='Advance notice for other items (days)'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='days_advance_rent',
            field=models.PositiveIntegerField(default=3, help_text='Advance notice for rent (days)'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='days_advance_taxes',
            field=models.PositiveIntegerField(default=5, help_text='Advance notice for taxes (days)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('PAST_DUE', 'Past Due (Payment Error)'), ('TRIALING', 'Trial Period')], default='ACTIVE', max_length=20),
        ),
    ]
