# Generated by Django 6.0.4 on 2026-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_lawyerprofile_goal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='average_monthly_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Average Expense'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='average_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Average Income'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='financial_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly Financial Goal (Optional)'),
        ),
    ]
