# Generated by Django 6.0.4 on 2026-05-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='type',
            field=models.CharField(choices=[('SOLO', 'Individual'), ('OFFICE', 'Escritório Coletivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='firmmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Dono'), ('LAWYER', 'Advogado Associado'), ('STAFF', 'Equipe de Apoio')], max_length=20),
        ),
    ]
