# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_plan_firmsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='type',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('OFFICE', 'Shared Office')], max_length=20),
        ),
        migrations.AlterField(
            model_name='firmmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('LAWYER', 'Associate Lawyer'), ('STAFF', 'Support Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='Current cycle expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='abacatepay_product_id',
            field=models.CharField(help_text='Product ID generated in the AbacatePay dashboard', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cycle',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SEMIANNUALLY', 'Semiannual'), ('ANNUALLY', 'Annual')], default='MONTHLY', max_length=20),
        ),
    ]
