# Generated by Django 6.0.6 on 2026-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0004_alter_firm_type_alter_firmmember_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'ordering': ['name']},
        ),
    ]
