# Generated by Django 6.0.6 on 2026-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0005_add_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (cus_*)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firmsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID (sub_*)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID (price_*)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='abacatepay_product_id',
            field=models.CharField(blank=True, help_text='Product ID generated in the AbacatePay dashboard', max_length=255, null=True, unique=True),
        ),
    ]
