# Generated by Django 6.0.6 on 2026-06-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0006_add_stripe_fields_to_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cycle',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMIANNUALLY', 'Semiannual'), ('ANNUALLY', 'Annual')], default='MONTHLY', max_length=20),
        ),
    ]
