# Generated by Django 6.0.6 on 2026-06-15 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0007_add_quarterly_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='End of free trial period', null=True),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='firms.plan'),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=20),
        ),
    ]
