# Generated by Django 6.0.4 on 2026-05-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ESTRUTURA', 'Estrutura'), ('PESSOAS', 'Pessoas'), ('IMPOSTOS', 'Impostos'), ('OPERACIONAL', 'Operacional')], default='OPERACIONAL', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='priority',
            field=models.CharField(choices=[('LEGAL', 'Legal / Crítico'), ('OPERACIONAL', 'Operacional'), ('OPCIONAL', 'Opcional')], default='OPERACIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('ONE_TIME', 'Única'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='ONE_TIME', max_length=20),
        ),
    ]
