# Generated by Django 6.0.4 on 2026-05-23 15:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedeferral',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='interest_rate_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Valor total da despesa', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='due_date',
            field=models.DateField(help_text='Data base ou primeiro vencimento'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParcelaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='expenses.expense')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddField(
            model_name='expensedeferral',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferrals', to='expenses.parceladespesa'),
        ),
    ]
