# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_expensedeferral_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total expense amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ESTRUTURA', 'Infrastructure'), ('PESSOAS', 'People'), ('IMPOSTOS', 'Taxes'), ('OPERACIONAL', 'Operational')], default='OPERACIONAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='due_date',
            field=models.DateField(help_text='Base date or first due date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='ONE_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='priority',
            field=models.CharField(choices=[('LEGAL', 'Legal / Critical'), ('OPERACIONAL', 'Operational'), ('OPCIONAL', 'Optional')], default='OPERACIONAL', max_length=20),
        ),
    ]
