# Generated by Django 5.2.1 on 2026-06-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_alter_expense_amount_alter_expense_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("PESSOAL_E_REMUNERACAO", "Pessoal e Remuneração"),
                    ("CUSTAS_PROCESSUAIS_E_JUDICIAIS", "Custas Processuais e Judiciais"),
                    ("FINANCEIRA", "Financeira"),
                    ("CAPACITACAO_E_DESENVOLVIMENTO", "Capacitação e Desenvolvimento"),
                    ("FISCAL_E_OBRIGACOES_LEGAIS", "Fiscal e Obrigações Legais"),
                    ("ESTRUTURA_E_OPERACAO", "Estrutura e Operação"),
                    ("TECNOLOGIA_E_ASSINATURA", "Tecnologia e Assinatura"),
                    ("MARKETING_E_AQUISICAO", "Marketing e Aquisição"),
                    ("MOBILIDADE_E_DESLOCAMENTO", "Mobilidade e Deslocamento"),
                    ("INVESTIMENTOS_NO_ESCRITORIO", "Investimentos no Escritório"),
                    ("A_CLASSIFICAR", "A Classificar"),
                    ("ESTRUTURA", "Estrutura"),
                    ("PESSOAS", "Pessoas"),
                    ("IMPOSTOS", "Impostos"),
                    ("OPERACIONAL", "Operacional"),
                ],
                default="OPERACIONAL",
                max_length=40,
            ),
        ),
    ]
