# Generated by Django 5.2.1 on 2026-06-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_alter_expense_category_expand_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
