# Generated by Django 6.0.6 on 2026-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-due_date']},
        ),
        migrations.AddIndex(
            model_name='parceladespesa',
            index=models.Index(fields=['due_date', 'is_paid'], name='parcela_due_paid_idx'),
        ),
    ]
