# Generated by Django 6.0.6 on 2026-06-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_add_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_reembolsavel',
            field=models.BooleanField(default=False, help_text='Custo adiantado pelo advogado e recuperável do cliente (ex: custas processuais)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('PESSOAL_E_REMUNERACAO', 'Pessoal e Remuneração'), ('FISCAL_E_OBRIGACOES_LEGAIS', 'Fiscal e Obrigações Legais'), ('CUSTAS_PROCESSUAIS_E_JUDICIAIS', 'Custas Processuais e Judiciais'), ('ESTRUTURA_E_OPERACAO', 'Estrutura e Operação'), ('TECNOLOGIA_E_ASSINATURA', 'Tecnologia e Assinaturas'), ('FINANCEIRA', 'Financeiro'), ('MARKETING_E_AQUISICAO', 'Marketing e Aquisição'), ('MOBILIDADE_E_DESLOCAMENTO', 'Mobilidade e Deslocamento'), ('INVESTIMENTOS_NO_ESCRITORIO', 'Investimentos no Escritório'), ('CAPACITACAO_E_DESENVOLVIMENTO', 'Capacitação e Desenvolvimento'), ('A_CLASSIFICAR', 'A Classificar')], default='A_CLASSIFICAR', max_length=40),
        ),
        migrations.AlterField(
            model_name='expense',
            name='priority',
            field=models.CharField(choices=[('CRITICA', 'Crítica'), ('ESPECIAL', 'Especial'), ('ALTA', 'Alta'), ('MEDIA_ALTA', 'Média-Alta'), ('MEDIA', 'Média'), ('MEDIA_BAIXA', 'Média-Baixa'), ('BAIXA', 'Baixa'), ('INDEFINIDA', 'Indefinida')], default='INDEFINIDA', max_length=20),
        ),
    ]
