# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='category',
            field=models.CharField(choices=[('MELHORIA', 'Feature Improvement'), ('NOVA_FUNC', 'New Feature'), ('BUG', 'Bug Report'), ('OUTRO', 'Other')], default='MELHORIA', max_length=20),
        ),
    ]
