# Generated by Django 6.0.6 on 2026-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestion_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-created_at']},
        ),
    ]
