# Generated by Django 6.0.4 on 2026-06-04 15:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0003_plan_firmsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutraEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_installment', models.BooleanField(default=False)),
                ('total_installments', models.PositiveIntegerField(default=1)),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outras_entradas', to='firms.firm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OutraEntradaInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('late_interest_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('outra_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='outras_entradas.outraentrada')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
    ]
