# Generated by Django 6.0.4 on 2026-05-28 22:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0005_remove_expensedeferral_expense_and_more'),
        ('firms', '0002_alter_firm_type_alter_firmmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(help_text='Mês/Ano de referência da simulação (usar dia 1 do mês)')),
                ('saldo_total_disponivel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_restante_pos_pagamentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioritization_simulations', to='firms.firm')),
            ],
            options={
                'verbose_name': 'Simulação de Prioridade',
                'verbose_name_plural': 'Simulações de Prioridade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSimulacaoPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_recomendacao', models.CharField(choices=[('RECOMENDADO', 'Pagamento Recomendado'), ('NAO_COBERTO', 'Não Coberto pelo Saldo')], max_length=20)),
                ('amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('late_interest_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_appearances', to='expenses.parceladespesa')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='motor.simulacaoprioridade')),
            ],
            options={
                'unique_together': {('simulacao', 'parcela')},
            },
        ),
    ]
