# Generated by Django 6.0.4 on 2026-05-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacaoprioridade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
