# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_alter_itemsimulacaoprioridade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulacaoprioridade',
            options={'ordering': ['-created_at'], 'verbose_name': 'Priority Simulation', 'verbose_name_plural': 'Priority Simulations'},
        ),
        migrations.AlterField(
            model_name='itemsimulacaoprioridade',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Card position on screen'),
        ),
        migrations.AlterField(
            model_name='itemsimulacaoprioridade',
            name='status_recomendacao',
            field=models.CharField(choices=[('RECOMENDADO', 'Recommended Payment'), ('NAO_COBERTO', 'Not Covered by Balance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacaoprioridade',
            name='reference_date',
            field=models.DateField(help_text='Simulation reference month/year (use the 1st day of the month)'),
        ),
    ]
