# Generated by Django 6.0.4 on 2026-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_clients_and_processes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('PF', 'Individual'), ('PJ', 'Legal Entity')], default='PF', max_length=2),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Active'), ('CONCLUIDO', 'Completed')], default='ATIVO', max_length=20),
        ),
    ]
