# Generated by Django 6.0.6 on 2026-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_client_type_alter_process_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-created_at']},
        ),
    ]
