# Generated by Django 6.0.6 on 2026-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_add_composite_indexes'),
        ('firms', '0005_add_composite_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['firm_id', 'name'], name='client_firm_name_idx'),
        ),
    ]
